# Composicao do programa de teste de uma lista genérica duplamente encadeada
# Este exemplo utiliza o arcabouço completo 

[Diretorios]
Nome        = TesteGrafo
PathDefault = ..\Fontes
err         = ..\Produto
obj			= ..\Objetos
h			= ..\Fontes
c			= ..\Fontes

[Modulos]
TestLis
Lista
Grafo

[BuildInicio]
/OUT:..\Produto\TesteGrafo.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
