# Composicao do programa de teste de uma lista genérica duplamente encadeada
# Este exemplo utiliza o arcabouço completo 

[Diretorios]
Nome        = TesteLista
PathDefault = ..\Fontes
err         = ..\Produto
obj			= ..\Objetos
h			= ..\Fontes
c			= ..\Fontes

[Modulos]
TestLis
Lista


[BuildInicio]
/OUT:..\Produto\TesteLista.exe
/INCREMENTAL:NO
/MACHINE:IX86

[BuildFim]
ArcaboucoTeste.lib

[Fim]
